name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install NGINX
        run: |
          sudo apt update
          sudo apt install -y nginx

      - name: Copy website files to NGINX directory
        run: |
          sudo rsync -av --exclude='.github' $GITHUB_WORKSPACE/ /var/www/html/

      - name: Start and enable NGINX
        run: |
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Check NGINX status
        run: |
          sudo systemctl status nginx
